trainer:
  log_every_n_steps: 5
  benchmark: True # faster
  max_epochs: 100
  precision: "16-mixed" # faster in razer

# extras:
#   ignore_warnings: False

callbacks:
  - early_stopping:
      - stopping_threshold: null # stop training immediately once the monitored quantity reaches this threshold
  - model_summary
  - rich_progress_bar
  - model_checkpoint:
      - monitor: "val_loss"
      - mode: "min"
      - filename: "{epoch:02d}-{val_loss:.2f}"
  # custom callbacks
  - _target_: utils.src.lightning.pl_log_callbacks.TensorboardLogTestTrainLoss
  # - _target_: utils.src.lightning.pl_log_callbacks.TensorboardLogAllWeigthsHist

data_module:
  _target_: src.dataset.XASDataModule
  compound: ${compound_name}
  split: material-splits
  task: train
  random_seed: 42
  batch_size: 128
  num_workers: 10
  persistent_workers: true
  use_cache: True
  pin_memory: True
  prefetch_factor: 4
