defaults:
  - hparams
  - trainer
  - _self_

hydra:
  run:
    dir: output/training/${name}/${element}_${type}

module:
  _target_: refactor.model.training.PlModule
  model: ${model}

data_module:
  _target_: refactor.model.training.LightningXASData
  ml_splits: ${ml_splits}
  batch_size: ${hparams.${name}.${type}.${element}.batch_size}
  scaler:
    _target_: hydra.utils.get_class
    path: refactor.data.ThousandScaler
  num_workers: 11
  persistent_workers: True

model:
  _target_: refactor.model.xasblock.XASBlock
  input_dim: 64
  hidden_dims: ${hparams.${name}.${type}.${element}.widths}
  output_dim: 141
