defaults:
  - hparams
  - trainer
  - _self_

hydra:
  run:
    dir: output/training/${name}/balanced/${element}_${type}

ml_splits:
  _target_: refactor.utils.io.DEFAULTFILEHANDLER.deserialize_json
  obj_class:
    _target_: hydra.utils.get_class
    path: refactor.data.ml_data.MLSplits
  supplemental_info:
    element: ${element}
    type: ${type}
    feature: ${feature}

data_module:
  _target_: refactor.model.training.LightningXASData
  ml_splits: ${ml_splits}
  batch_size: ${hparams.${name}.${type}.${element}.batch_size}
  x_scaler:
    _target_: hydra.utils.get_class
    path: refactor.data.ThousandScaler
  y_scaler:
    _target_: hydra.utils.get_class
    path: refactor.data.ThousandScaler
  num_workers: 11
  persistent_workers: True
  shuffle: True # very important for MergedMLSplits (used in UniversalXAS)

model:
  _target_: refactor.model.xasblock.XASBlock
  input_dim: 64
  hidden_dims: ${hparams.${name}.${type}.${element}.widths}
  output_dim: 141 # TODO: remove hardcoding
