defaults:
  - tunedUniversalXAS
  - _self_

freeze: ??

hydra:
  run:
    dir: output/training/${name}/freeze_${freeze}/${element}_${type}

module:
  _target_: omnixas.model.trained_model.TrainedModelLoader.load_model_for_finetuning
  tag:
    _target_: omnixas.model.trained_model.ModelTag
    name: universalXAS
    element: All
    type: FEFF
  freeze_first_k_layers: ${freeze} # 0-3 (for xasblocks)
