defaults:
  - tunedUniversalXAS
  - _self_

module:
  _target_: refactor.model.trained_model.TrainedModelLoader.load_model_for_finetuning
  tag:
    _target_: refactor.model.trained_model.ModelTag
    name: universalXAS
    element: All
    type: FEFF
  freeze_first_k_layers: 0 # 0-3 (for xasblocks)
