defaults:
  - tunedUniversalXAS
  - _self_

hydra:
  run:
    dir: output/training/no_early_stop/${name}/${element}_${type}

trainer:
  callbacks:
    - ${callbacks.lr_finder}
    - ${callbacks.lr_monitor}
    - ${callbacks.model_checkpoint}
    - ${callbacks.train_val_loss}
    # - ${callbacks.early_stopping}
