defaults:
  - tunedUniversalXAS
  - _self_

hydra:
  run:
    dir: output/training/${name}/v2/${element}_${type}

module:
  _target_: omnixas.model.trained_model.TrainedModelLoader.load_model_for_finetuning
  tag:
    _target_: omnixas.model.trained_model.ModelTag
    name: universalXAS
    element: All
    type: FEFF
  disable_dropout: true
  freeze_first_k_layers: 0 # 0-3 (for xasblocks)
  reset_batchnorm: false