defaults:
  - defaults
  - _self_

name: tunedUniversalXAS
element: ???
type: ??? # FEFF, VASP ..
feature: m3gnet # m3gnet, ACSF...

module:
  _target_: omnixas.model.trained_model.TrainedModelLoader.load_model
  tag:
    _target_: omnixas.model.trained_model.ModelTag
    name: universalXAS
    element: All
    type: FEFF

trainer:
  callbacks:
    - ${callbacks.lr_finder}
    - ${callbacks.lr_monitor}
    - ${callbacks.model_checkpoint}
    - ${callbacks.train_val_loss}
    # - ${callbacks.early_stopping} # early stopping can be triggered prematurely in fine-tuning
