defaults:
  - defaults
  - _self_

name: universalXAS
element: All # placeholder for hparms
type: FEFF # FEFF, VASP ..
feature: m3gnet # m3gnet, ACSF...

ml_splits:
  _target_: omnixas.utils.constants.FEFFSplits

module:
  _target_: omnixas.model.training.PlModule
  model: ${model}
