ml_data:
  anamoly_filter_std_cutoff:
    FEFF: 2.5
    VASP: 5.0
    SOAP: 2.5
    ACSF: 2.5

data_module:
  _target_: src.data.ml_data.XASPlData
  query:
    _target_: src.data.ml_data.DataQuery
    compound: ${compound_name}
    simulation_type: ${simulation_type}
    # compound: ${compound_name}
    # simulation_type: ${simulation_type}
    # split: material
  # data_dir: "dataset/ML-231009/${compound_name}_K-edge_${simulation_type}_XANES/material-splits/data"
  random_seed: 42
  batch_size: ${hparams.${simulation_type}.${compound_name}.batch_size}
  # num_workers: 10
  # persistent_workers: true
  # use_cache: True
  # pin_memory: True
  # prefetch_factor: 4
  # drop_last: False
  split_fractions: [0.8, 0.1, 0.1]

feature_dims:
  input_dim:
    FEFF: 64
    VASP: 64
    SOAP: 17
    ACSF: 4
  output_dim:
    FEFF: 141
    VASP: 141
    SOAP: 141
    ACSF: 141
