callbacks:
  - _target_: lightning.pytorch.callbacks.lr_finder.LearningRateFinder
  - _target_: lightning.pytorch.callbacks.early_stopping.EarlyStopping
    monitor: val_loss
    patience: 50
    mode: min
    verbose: False
  - _target_: utils.src.lightning.loggers.tb.log_train_val_loss.TensorboardLogTestTrainLoss
