data_module:
  _target_: src.data.pl_data.XASData
  # _target_: src.xas_data.XASData
  query:
    _target_: src.data.pl_data.DataQuery
    compound: ${compound_name}
    simulation_type: ${simulation_type}
    # compound: ${compound_name}
    # simulation_type: ${simulation_type}
    # split: material
  # data_dir: "dataset/ML-231009/${compound_name}_K-edge_${simulation_type}_XANES/material-splits/data"
  random_seed: 42
  batch_size: 128
  num_workers: 10
  persistent_workers: true
  use_cache: True
  pin_memory: True
  prefetch_factor: 4
  drop_last: False
