defaults:
  - _self_
  - data
  - model
  # - callbacks
  - optuna
  - transformations
  - compounds
  - paths
  - experiment
  - dscribe
  - hydra: default
  - logger: tensorboard

hydra:
  searchpath:
    - pkg://utils/src/hydra/configs
    - utils/src/hydra/configs

  # You can also use file based schema:
  # - file:///etc/my_app
  # - file://${oc.env:HOME}/.my_app
