defaults:
  - data
  - model
  # - callbacks
  - optuna
  - transformations
  - compounds
  - paths
  - experiment
  - dscribe
  - hydra: default
  - logger: tensorboard
  - hparams
  - _self_

hydra:
  searchpath:
    - pkg://utils/src/hydra/configs
    - utils/src/hydra/configs

  run:
    dir: ${paths.log_dir}/${task_name}/${model_name}/${now:%Y-%m-%d_%H-%M-%S}

  # You can also use file based schema:
  # - file:///etc/my_app
  # - file://${oc.env:HOME}/.my_app
