defaults:
  # - defaults
  # - debug
  - mps # trainer is specified underneath
  - callbacks
  - _self_

# task_name: ${model.model.widths}
task_name: ${compound_name}-${simulation_type}

compound_name: Cu # Cu-O # Ti-O
simulation_type: FEFF
tags:
  - ${compound_name}
  - ${simulation_type}

trainer:
  max_epochs: 500
  log_every_n_steps: 1

optuna:
  study_name: ${compound_name}-${simulation_type}
  storage: sqlite:///${optuna.study_name}.db
  params:
    min_width: 100
    max_width: 100
    step_width: 10
    min_depth: 1
    max_depth: 1
  load_if_exists: True
  n_trials: 1

callbacks:
  model_summary:
    max_depth: 2
  model_checkpoint:
    mode: "min"
    save_last: True
  early_stopping:
    monitor: val_loss
    min_delta: 0.
    patience: 10
    verbose: False
