defaults:
  # - defaults
  # - debug
  - mps # trainer is specified underneath
  - callbacks
  - _self_

# task_name: ${model.model.widths}
task_name: ${compound_name}-${simulation_type}
model:
  model:
    widths: [64] # [64, 100, 100, 100]

compound_name: Cu # Cu-O # Ti-O
simulation_type: FEFF
tags:
  - ${compound_name}
  - ${simulation_type}

trainer:
  max_epochs: 100
  log_every_n_steps: 10

optuna:
  study_name: ${compound_name}-${simulation_type}
  storage: sqlite:///${optuna.study_name}.db
  params:
    min_width: 10
    max_width: 200
    step_width: 10
  load_if_exists: True
  n_trials: 500

callbacks:
  early_stopping:
    min_delta: 0.
    verbose: True
  model_summary:
    max_depth: 10
  model_checkpoint:
    mode: "min"
    save_last: True