model_name: per_compound_tl

model: ${named_models.${model_name}}

name_queries:
  per_compound:
    _target_: src.data.ml_data.DataQuery
    compound: ${compound}
    simulation_type: ${simulation_type}

  universal:
    _target_: src.data.ml_data.DataQuery
    compound: "ALL"
    simulation_type: FEFF # no univ for VASP yet

named_models:
  default:
    _target_: utils.src.lightning.pl_module.PLModule
    model:
      _target_: src.models.xas_fc.FC_XAS
      widths: [200]
      input_dim: ${feature_dims.input_dim.${simulation_type}}
      output_dim: ${feature_dims.output_dim.${simulation_type}}
      compound: ${compound_name}
      simulation_type: ${simulation_type}
    learning_rate: 0.001

  per_compound_tl:
    _target_: utils.src.lightning.pl_module.PLModule
    model:
      _target_: src.models.xas_fc.FC_XAS
      widths: ${hparams.${simulation_type}.${compound_name}.widths}
      output_dim: ${feature_dims.output_dim.${simulation_type}}
      compound: ${compound_name}
      simulation_type: ${simulation_type}

  universal_tl:
    _target_: utils.src.lightning.pl_module.PLModule
    model:
      _target_: src.models.xas_fc.FC_XAS
      widths: ${hparams.${simulation_type}.ALL.widths}
      output_dim: ${feature_dims.output_dim.${simulation_type}}
      compound: ${compound_name}
      simulation_type: ${simulation_type}

  ft_tl:
    _target_: src.models.trained_models.PreTrainedFCXASModel
    query: ${name_queries.universal}
    name: universal_tl
    widths: ${named_models.universal_tl.model.widths}
    input_dim: ${feature_dims.input_dim.${simulation_type}}
    output_dim: ${feature_dims.output_dim.${simulation_type}}
    compound: ${compound_name}
    simulation_type: ${simulation_type}
