serialization:
  ElementSpectrum:
    directory: dataset/spectra/{type}/{element}
    filename: "{material.id}_site_{index_string}_{element}_{type}.json"

  MLData:
    directory: dataset/ml_data/{type}/{element} # for per element saving
    filename: "{material.id}_site_{index_string}_{element}_{type}.json"

  MLSplits:
    directory: dataset/ml_data/splits
    filename: "{element}_{type}_{feature}.json"

  TrainedXASBlock:
    directory: output/training/{name}/{element}_{type}/checkpoints # perf test
    filename: "best{}.ckpt" # best/last{}.ckpt
