serialization:
  ElementSpectrum:
    directory: dataset/spectra/{type}/{element}
    filename: "{material.id}_site_{index_string}_{element}_{type}.json"

  M3GNetSiteFeature:
    directory: dataset/features/{type}/{element}
    filename: "m3gnet_{material.id}_site_{index_string}_{element}_{type}.json"

  MLData:
    directory: dataset/ml_data/{type}/{element} # for per element saving
    filename: "{material.id}_site_{index_string}_{element}_{type}.json"

  MLSplits:
    directory: dataset/ml_data/splits
    filename: "{element}_{type}_m3gnet.json"

  TrainedXASBlock:
    # directory: output/training/{name}/{element}_{type}/checkpoints
    # directory: output/io/training/{name}/{element}_{type}/checkpoints
    # directory: output/io/training/uncenteredRoboustScaler/{name}/{element}_{type}/checkpoints
    directory: output/io/training/multiScale/{name}/{element}_{type}/checkpoints
    filename: "{}.ckpt"
