defaults:
  - _self_

transformations:
  quarter_eV_resolution: 0.25 # used for interpolation
  e_range_diff: 35 # energy range used

  e_start:
    Co: 7709.282
    Cr: 5989.168
    Cu: 8983.173
    # Cu: 8990
    Fe: 7111.23
    Mn: 6537.886
    Ni: 8332.181
    Ti: 4964.504
    V: 5464.097
    ALL: 0 # dummy for universal e_start
    # PREVIOUS VALUES
    # Ti: 4970
    # Cu: 0

  emperical_offset:
    VASP:
      # this is with experiment and alightment with FEFF
      Ti: 5114.08973
      Cu: 9499.797
      # This is based on the comparision with experiment
      # Ti: 5108.58973
      # Cu: 9492.797 

  gamma:
    Ti: 0.89 # put same value in trucation offset
    # Cu: 3 # arbitrary to align with feff
    Cu: 3.458 # 1.729 # or 3.458 #Based on email conv with J.K.

  e_core:
    Ti: -4864.0371
    Cu: -8850.2467
